apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::908819106230:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-H6FDZMS0WIKP
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::908819106230:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-30T21:47:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1624"
  uid: e9ecd03c-7550-43e7-9050-3e7365c9b7af
